name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        run: echo Yessssssssssss

      - name: Get branch name (merge)
        shell: bash
        if: github.event_name != 'pull_request'
        run: echo Yessssssssssss
