name: CI
on:
  push:
    branches: [ "main" , "test"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request '
        run: echo ${{ github.ref_name }}

